import {finite,valueAt} from './data.js';
export function snowCategory(mm){if(!finite(mm)||mm<0)return null;mm=Math.round(mm*1e6)/1e6;if(mm===0)return 'No snow';if(mm<2)return 'D1';if(mm<=20)return 'D2';if(mm<=50)return 'D3';return 'E';}
export function eventHours(start,end){const a=Date.parse(start),b=Date.parse(end);if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a||b-a>168*3600000||a%3600000!==0||b%3600000!==0)throw new Error('Choose whole UTC hours with an end after the start, up to seven days apart.');return Array.from({length:(b-a)/3600000},(_,i)=>new Date(a+(i+1)*3600000).toISOString().replace('.000Z','Z'));}
export function analyseEvent(model,start,end){
 const times=eventHours(start,end);const snow=times.map(t=>valueAt(model,'snowfall',t));const precipitation=times.map(t=>valueAt(model,'precipitation',t));const air=times.map(t=>valueAt(model,'temperature_2m',t));const ground=times.map(t=>valueAt(model,'soil_temperature_0cm',t));const available=snow.filter(finite).length;
 const snowMm=available===times.length?snow.reduce((a,b)=>a+b,0)*10:null;const totalPrecip=precipitation.every(finite)?precipitation.reduce((a,b)=>a+b,0):null;
 let signals=0,assessed=0;const reasons=new Set();
 for(let i=0;i<times.length;i++){if(!finite(ground[i]))continue;const prior=[];for(let back=0;back<6;back++){const t=new Date(Date.parse(times[i])-back*3600000).toISOString().replace('.000Z','Z');prior.push(valueAt(model,'precipitation',t));}if(!prior.every(finite))continue;assessed++;if(ground[i]>0)continue;let wet=prior.reduce((a,b)=>a+b,0)>=.1;let thaw=false;for(let back=0;back<6;back++){const hour=Date.parse(times[i])-back*3600000;const t=new Date(hour).toISOString().replace('.000Z','Z'),before=new Date(hour-3600000).toISOString().replace('.000Z','Z');const a=valueAt(model,'snow_depth',before),b=valueAt(model,'snow_depth',t),temp=valueAt(model,'temperature_2m',t);if(finite(a)&&finite(b)&&finite(temp)&&a-b>=.1&&temp>0)thaw=true;}if(wet||thaw){signals++;if(wet)reasons.add('precipitation in the previous six hours');if(thaw)reasons.add('falling snow depth in above-zero air');}}
 return {snowMm,category:snowCategory(snowMm),snowHours:available,hours:times.length,precipitation:totalPrecip,minAir:air.every(finite)?Math.min(...air):null,minGround:ground.every(finite)?Math.min(...ground):null,signalHours:signals,assessedHours:assessed,reasons:[...reasons]};
}
